site:
  title: Redpanda Docs
  start_page: api:ROOT:cloud-api.adoc
  url: http://localhost:5002
content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/redpanda-data/documentation
    branches: [v/*, site-search, main, shared]
ui:
  bundle:
    url: https://github.com/redpanda-data/docs-ui/releases/download/1.6.0-beta/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  extensions:
  - '@asciidoctor/tabs'
  - '@redpanda-data/docs-extensions-and-macros/macros/glossary'
  - '@redpanda-data/docs-extensions-and-macros/macros/config-ref'
  - '@redpanda-data/docs-extensions-and-macros/macros/helm-ref'
antora:
  extensions:
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/unlisted-pages'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/add-global-attributes'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/aggregate-terms'
output:
  clean: true